openapi: "3.1.0"
info:
  title: Product Management
  version: 0.0.1
paths:
  /products:
    post:
      tags:
        - Product
      operationId: createNewProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: "A product was successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateNewProductResponse"

  /product/{id}:
    put:
      tags:
        - Product
      operationId: setProduct
      parameters:
        - name: id
          in: path
          description: ID of a product to update
          required: true
          schema:
            $ref: "#/components/schemas/ProductId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        204:
          description: "The product was successfully updated"
        201:
          description: "The product was successfully created"
    delete:
      tags:
        - Product
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: ID of a product to update
          required: true
          schema:
            $ref: "#/components/schemas/ProductId"
      responses:
        204:
          description: "The product was deleted"

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 256
        price:
          type: number
          minimum: 0
        quantity:
          type: integer
          minimum: 0
      required:
        - name

    ProductId:
      description: ID of a product
      type: string
      minLength: 1
      maxLength: 64

    CreateNewProductResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ProductId"
      required:
        - id
